plugins: [jekyll-paginate]

name: charlottebond.co.uk
highlighter: true

recent_limit: 8
paginate: 12
paginate_path: "/blog/page:num/"

server_name: www.charlottebond.co.uk
server_username: nathan
server_dir: /home/nathan/Websites/CharlotteCourtney

production_url: http://www.charlottebond.co.uk

exclude: [Rakefile]
